source settings/config.sh

PORT_FOR_CLIENT=$GLOBAL_LOAD_BALANCER_PORT_FOR_CLIENT
PORT_FOR_SERVER=$GLOBAL_LOAD_BALANCER_PORT_FOR_SERVER
PORT_FOR_CACHE=$GLOBAL_LOAD_BALANCER_PORT_FOR_CACHE
METADATA_IP=$GLOBAL_METADATA_IP
METADATA_PORT=$GLOBAL_METADATA_PORT

echo "Run load_balancer"
echo "Port for client: $PORT_FOR_CLIENT"
echo "Port for servers: $PORT_FOR_SERVER"
echo "Port for caches: $PORT_FOR_CACHE"
echo "Metadata IP: $METADATA_IP"
echo "Metadata port: $METADATA_PORT"
echo ""
sleep 1
build/bin/load_balancer basic 0.0.0.0 $PORT_FOR_CLIENT 0.0.0.0 $PORT_FOR_SERVER 0.0.0.0 $PORT_FOR_CACHE $METADATA_IP $METADATA_PORT